"use client";

import "./styles/globals.scss";
import type { Metadata } from "next";
import { QueryClientProvider } from "@tanstack/react-query";
import { QueryClient } from "@tanstack/query-core";

export const metadata: Metadata = {
  title: "Question List",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="fa" dir="rtl">
        <body>{children}</body>
      </html>
    </QueryClientProvider>
  );
}
